// The map every flow on this page is drawn on. Boxes, zones and pods are fixed;
// a scenario is only an ordered list of hops across them, so the reader learns
// the territory once and afterwards watches a pen move over something familiar.

export interface Rect {
  x: number
  y: number
  w: number
  h: number
}

export interface Zone extends Rect {
  label: string
}

export interface Box extends Rect {
  label: string
  sub?: string
  kind: "declared" | "built" | "external"
}

export interface Step {
  from: string
  to: string
  // Boxes this step involves but has no arrow to, so they light with it
  // instead of reading as untouched.
  also?: string[]
  label: string
  kind: "declared" | "built" | "token" | "gate"
  dashed?: boolean
  text: string
  who: string
  tokenName: string
  claims: [string, string][]
}

export interface Scenario {
  key: string
  name: string
  yaml: [string, "d" | "c"][]
  steps: Step[]
}

const SPIFFE = "spiffe://homelab.local/ns/orders/sa/orders-api"

export const ZONES: Record<string, Zone> = {
  cluster: { x: 216, y: 20, w: 596, h: 540, label: "the cluster" },
  node: { x: 416, y: 112, w: 352, h: 286, label: "node · work-2" },
  clouds: { x: 856, y: 20, w: 368, h: 320, label: "the clouds" },
}

export const PODS: Record<string, Zone> = {
  podA: { x: 428, y: 196, w: 178, h: 192, label: "orders-api pod" },
  podB: { x: 648, y: 196, w: 112, h: 192, label: "billing-api pod" },
}

export const BOXES: Record<string, Box> = {
  commit: {
    x: 16,
    y: 52,
    w: 146,
    h: 46,
    label: "The commit",
    sub: "YAML in git",
    kind: "declared",
  },
  browser: {
    x: 16,
    y: 132,
    w: 146,
    h: 46,
    label: "Browser",
    sub: "holds no token",
    kind: "external",
  },
  argocd: {
    x: 232,
    y: 50,
    w: 158,
    h: 44,
    label: "ArgoCD",
    sub: "applies what git says",
    kind: "built",
  },
  xp: { x: 470, y: 50, w: 168, h: 44, label: "Crossplane", sub: "builds the rest", kind: "built" },
  spireS: {
    x: 232,
    y: 124,
    w: 152,
    h: 44,
    label: "SPIRE server",
    sub: "the only signing key",
    kind: "built",
  },
  spireA: {
    x: 452,
    y: 142,
    w: 150,
    h: 42,
    label: "SPIRE agent",
    sub: "asks kubelet",
    kind: "built",
  },
  sidecar: {
    x: 440,
    y: 222,
    w: 154,
    h: 40,
    label: "credential sidecar",
    sub: "keeps files fresh",
    kind: "built",
  },
  app: {
    x: 440,
    y: 280,
    w: 154,
    h: 40,
    label: "orders-api",
    sub: "no credential in it",
    kind: "declared",
  },
  envoyO: { x: 440, y: 338, w: 154, h: 40, label: "Envoy", sub: "gates 1-2", kind: "built" },
  callee: { x: 658, y: 222, w: 92, h: 40, label: "billing-api", sub: "roles", kind: "declared" },
  envoyI: { x: 658, y: 338, w: 92, h: 40, label: "Envoy", sub: "gate 3", kind: "built" },
  oidc: {
    x: 232,
    y: 418,
    w: 254,
    h: 44,
    label: "OIDC JWKS",
    sub: "public, keys only",
    kind: "built",
  },
  istio: {
    x: 232,
    y: 482,
    w: 254,
    h: 44,
    label: "Istio policy",
    sub: "Sidecar + PeerAuthentication",
    kind: "built",
  },
  spaWeb: { x: 496, y: 418, w: 124, h: 44, label: "orders-web", sub: "nginx", kind: "declared" },
  podRep: { x: 640, y: 418, w: 128, h: 44, label: "reports-api", sub: "scp", kind: "declared" },
  binding: {
    x: 496,
    y: 482,
    w: 272,
    h: 44,
    label: "binding Secrets",
    sub: "ARNs, no credentials",
    kind: "built",
  },
  entra: {
    x: 872,
    y: 50,
    w: 336,
    h: 46,
    label: "Microsoft Entra",
    sub: "registration, federated credential",
    kind: "external",
  },
  sts: {
    x: 872,
    y: 124,
    w: 336,
    h: 42,
    label: "AWS STS",
    sub: "AssumeRoleWithWebIdentity",
    kind: "external",
  },
  iam: {
    x: 872,
    y: 190,
    w: 336,
    h: 42,
    label: "IAM role",
    sub: "trust = one SPIFFE ID",
    kind: "built",
  },
  s3: { x: 872, y: 256, w: 336, h: 46, label: "S3 bucket", sub: "and nothing else", kind: "built" },
}

export const SCENARIOS: Scenario[] = [
  {
    key: "provision",
    name: "One commit, day zero",
    yaml: [
      ["kind: ObjectStorage", "d"],
      ["metadata: { name: order-docs }", "d"],
      ["---", "c"],
      ["kind: Api", "c"],
      ["metadata:", "c"],
      ["  name: orders-api", "c"],
      ["spec:", "c"],
      ["  parameters:", "c"],
      ["    objectStorageRefs:", "d"],
      ["      - name: order-docs", "d"],
      ["    consumes:", "d"],
      ["      - app: billing-api", "d"],
      ["    provides:", "d"],
      ["      - name: ledger", "d"],
      ["        auth: workload", "d"],
      ["        allowedCallers:", "d"],
      ["          - app: orders-api", "d"],
    ],
    steps: [
      {
        from: "commit",
        to: "argocd",
        label: "git push",
        kind: "declared",
        text: "The workspace is committed to git.",
        who: "By the <b>app team</b> or <b>Launchpad</b>.",
        tokenName: "What was asked for",
        claims: [
          ["a bucket", "ObjectStorage"],
          ["access to it", "objectStorageRefs"],
          ["a callee", "consumes"],
          ["an interface", "provides + allowedCallers"],
        ],
      },
      {
        from: "argocd",
        to: "xp",
        label: "applies the XRs",
        kind: "built",
        text: "Applied to the cluster and kept there.",
        who: "By <b>ArgoCD</b>. Anything deleted by hand comes back.",
        tokenName: "Now in the cluster",
        claims: [
          ["kinds", "ObjectStorage, Api"],
          ["prune", "true"],
          ["selfHeal", "true"],
        ],
      },
      {
        from: "xp",
        to: "s3",
        also: ["iam"],
        label: "bucket + role",
        kind: "built",
        text: "The bucket, plus an IAM role only this pod can assume, limited to that bucket.",
        who: "Built by <b>Crossplane</b>, alongside the next three steps.",
        tokenName: "Created in AWS",
        claims: [
          ["trust sub", `<em>${SPIFFE}</em>`],
          ["trust aud", "sts.amazonaws.com"],
          ["policy", "this bucket only"],
          ["ARN", "derived, not read back"],
        ],
      },
      {
        from: "xp",
        to: "entra",
        label: "registration",
        kind: "built",
        text: "An Entra app registration trusting the same SPIFFE ID, with one app role per interface.",
        who: "Built by <b>Crossplane</b>.",
        tokenName: "Created in Entra",
        claims: [
          ["issuer", "https://oidc.mattjarrett.dev"],
          ["sub", "the SPIFFE ID"],
          ["aud", "api://AzureADTokenExchange"],
          ["token version", "2, or the issuer is wrong"],
        ],
      },
      {
        from: "xp",
        to: "istio",
        label: "egress + mTLS",
        kind: "built",
        text: "The consumes list becomes the pod's allowed egress, and strict mTLS keeps out anything outside the mesh.",
        who: "Built by <b>Crossplane</b>. The team writes no Istio config.",
        tokenName: "Created in the cluster",
        claims: [
          ["from consumes", "Sidecar egress, REGISTRY_ONLY"],
          ["on every workload", "PeerAuthentication, STRICT"],
          ["default", "nothing is reachable"],
        ],
      },
      {
        from: "xp",
        to: "binding",
        label: "one per ref",
        kind: "built",
        text: "One Secret per ref, holding the role ARN and bucket name but no credentials.",
        who: "Built by <b>Crossplane</b>.",
        tokenName: "In the binding Secret",
        claims: [
          ["type", "s3"],
          ["role-arn", "arn:aws:iam::…:role/crossplane/…"],
          ["bucket", "platform-orders-order-docs"],
          ["credentials", "<em>none</em>"],
        ],
      },
      {
        from: "xp",
        to: "app",
        label: "Deployment",
        kind: "built",
        text: "The pod: the app, the credential sidecar, and an init container per binding.",
        who: "Built by <b>Crossplane</b>. The team only picks the image.",
        tokenName: "Rendered into the pod",
        claims: [
          ["containers", "app + credential sidecar"],
          ["init", "waits on /bindings"],
          ["volumes", "SPIFFE CSI socket, bindings"],
        ],
      },
      {
        from: "binding",
        to: "sidecar",
        label: "mounted at /bindings",
        kind: "built",
        text: "The init containers wait for the binding files, which are usually already there, so this takes seconds.",
        who: "Ordered by <b>Kubernetes</b>.",
        tokenName: "What it waits for",
        claims: [
          ["path", "/bindings/object-storage-order-docs/type"],
          ["status", "<em>Init:0/3</em>, a few seconds"],
          ["then", "images pull"],
        ],
      },
      {
        from: "sidecar",
        to: "sidecar",
        label: "first exchange",
        kind: "built",
        text: "The sidecar fetches its first SVID and exchanges it with both clouds.",
        who: "Started by the <b>kubelet</b>.",
        tokenName: "First exchange",
        claims: [
          ["AWS", "credentials file written"],
          ["Entra", "token file written"],
        ],
      },
      {
        from: "app",
        to: "app",
        label: "3/3 Running",
        kind: "declared",
        text: "The app starts last, with every file it needs already in place.",
        who: "Running as the <b>app team</b> declared it.",
        tokenName: "Ready",
        claims: [
          ["status", "3/3 Running"],
          ["waited on", "Crossplane, then both clouds"],
          ["secrets typed by a human", "none"],
        ],
      },
    ],
  },

  {
    key: "workload",
    name: "API calls API",
    yaml: [
      ["orders-api", "c"],
      ["consumes:", "d"],
      ["  - app: billing-api", "d"],
      ["", "c"],
      ["billing-api", "c"],
      ["provides:", "d"],
      ["  - name: ledger", "d"],
      ["    auth: workload", "d"],
      ["    allowedCallers:", "d"],
      ["      - app: orders-api", "d"],
    ],
    steps: [
      {
        from: "spireS",
        to: "spireA",
        label: "signs the SVID",
        kind: "built",
        text: "Identity starts at the one server that holds the signing key.",
        who: "Built by <b>SPIRE</b>. A compromised node cannot mint an identity.",
        tokenName: "Where identity starts",
        claims: [
          ["trust domain", "homelab.local"],
          ["signing key", "server only"],
          ["agent holds", "no key"],
        ],
      },
      {
        from: "spireA",
        to: "sidecar",
        label: "CSI socket",
        kind: "built",
        text: "The sidecar asks the agent over a mounted socket, and the agent checks with kubelet which pod is asking.",
        who: "A <b>copied manifest</b> gets nothing.",
        tokenName: "JWT-SVID",
        claims: [
          ["over", "Workload API, CSI-mounted socket"],
          ["sub", SPIFFE],
          ["aud", "<em>api://AzureADTokenExchange</em>"],
          ["exp", "in 5 minutes"],
        ],
      },
      {
        from: "sidecar",
        to: "sidecar",
        label: "writes the file",
        kind: "built",
        text: "The token is written to a shared file every 240s.",
        who: "By the <b>sidecar</b>.",
        tokenName: "At rest",
        claims: [
          ["file", "/entra-identity/token"],
          ["written by", "the sidecar"],
          ["read by", "the app"],
          ["calls Entra", "<em>never</em>"],
        ],
      },
      {
        from: "app",
        to: "entra",
        label: "client_assertion",
        kind: "token",
        text: "The app's Azure SDK swaps that file for an access token, as it would on AKS.",
        who: "Using a file and env vars <b>the platform</b> provided.",
        tokenName: "Presented to Entra",
        claims: [
          ["assertion", "the file on disk"],
          ["client_id", "AZURE_CLIENT_ID"],
          ["token file", "AZURE_FEDERATED_TOKEN_FILE"],
          ["scope", "api://billing-api/.default"],
        ],
      },
      {
        from: "entra",
        to: "oidc",
        label: "fetch public keys",
        kind: "built",
        dashed: true,
        text: "The signature is checked against the cluster's published keys.",
        who: "By <b>Entra</b>. No secret was shared.",
        tokenName: "Being verified",
        claims: [
          ["signature", "against published JWKS"],
          ["sub", "literal match, no wildcards"],
          ["aud", "literal match"],
        ],
      },
      {
        from: "entra",
        to: "app",
        label: "access token",
        kind: "token",
        text: "The access token carries the ledger role, because billing-api lists orders-api as a caller.",
        who: "Granted by <b>billing-api's own file</b>.",
        tokenName: "Entra access token",
        claims: [
          ["aud", "api://billing-api"],
          ["roles", '<em>["ledger"]</em>'],
          ["appid", "orders-api"],
          ["exp", "in 1 hour"],
        ],
      },
      {
        from: "envoyO",
        to: "envoyO",
        label: "gates 1 + 2",
        kind: "gate",
        text: "The caller's Envoy only lets the call out if billing-api is in its egress list.",
        who: "Enforced by <b>Istio</b>. A refused call is a 502 inside the pod.",
        tokenName: "Mesh check",
        claims: [
          ["gate 1", "Sidecar egress, REGISTRY_ONLY"],
          ["gate 2", "host in the registry"],
          ["fails as", "blackholed at source"],
        ],
      },
      {
        from: "envoyO",
        to: "envoyI",
        label: "mTLS",
        kind: "gate",
        text: "The callee's Envoy requires a mesh mTLS certificate and never reads the token.",
        who: "Enforced by <b>Istio</b>.",
        tokenName: "Peer identity",
        claims: [
          ["principal", SPIFFE],
          ["gate 3", "PeerAuthentication, mTLS"],
          ["fails as", "connection reset"],
        ],
      },
      {
        from: "envoyI",
        to: "callee",
        label: "roles check",
        kind: "declared",
        text: "billing-api checks the roles claim, because only it knows which routes need ledger.",
        who: "Gate 4, in <b>app code</b>.",
        tokenName: "What the app sees",
        claims: [
          ["roles", '<em>["ledger"]</em>'],
          ["route", "GET /ledger"],
          ["result", "200"],
        ],
      },
    ],
  },

  {
    key: "pkce",
    name: "SPA sign-in (PKCE)",
    yaml: [
      ["orders-web", "c"],
      ["userAuth:", "d"],
      ["  client: orders-api", "d"],
      ["  scopes: [profile]", "d"],
      ["apiProxies:", "d"],
      ["  - app: orders-api", "d"],
      ["    path: /api", "d"],
      ["host: orders.example.dev", "d"],
    ],
    steps: [
      {
        from: "browser",
        to: "entra",
        label: "code_challenge S256",
        kind: "token",
        text: "The redirect to Entra carries a hash of a secret the client just made. The secret stays behind.",
        who: "Needed because a <b>browser cannot keep a secret</b>.",
        tokenName: "Authorize request",
        claims: [
          ["client_id", "public, by design"],
          ["code_challenge", "<em>SHA-256(verifier)</em>"],
          ["method", "S256"],
          ["redirect_uri", "derived from host"],
        ],
      },
      {
        from: "entra",
        to: "browser",
        label: "authorization code",
        kind: "token",
        text: "The person signs in and a single-use code comes back in the URL.",
        who: "Sent to an <b>allow-listed</b> redirect URI.",
        tokenName: "In the URL",
        claims: [
          ["code", "single use"],
          ["stolen?", "worthless without the verifier"],
        ],
      },
      {
        from: "browser",
        to: "spaWeb",
        label: "POST /api/auth",
        kind: "declared",
        text: "The page posts the code to the app's backend through the SPA's proxy.",
        who: "Routed by the <b>Spa composition</b>.",
        tokenName: "On the wire",
        claims: [
          ["code", "in the request body"],
          ["Host", "orders-api.orders.svc"],
          ["X-Forwarded-Host", "orders.example.dev"],
        ],
      },
      {
        from: "spaWeb",
        to: "envoyO",
        label: "gates 1-3",
        kind: "gate",
        text: "The call passes the same mesh gates as any other.",
        who: "Enforced by <b>Istio</b> from apiProxies.",
        tokenName: "Mesh check",
        claims: [
          ["gates", "egress, registry, mTLS"],
          ["fails as", "502 or connection reset"],
        ],
      },
      {
        from: "envoyO",
        to: "app",
        label: "",
        kind: "declared",
        text: "The backend holds the original secret, which proves it started this sign-in.",
        who: "That is all <b>PKCE</b> proves. It says nothing about which app is asking.",
        tokenName: "Held by the backend",
        claims: [
          ["code_verifier", "43-128 random chars"],
          ["left the app", "<em>never</em>"],
        ],
      },
      {
        from: "app",
        to: "entra",
        label: "code + verifier",
        kind: "token",
        text: "The secret is hashed and compared to the stored hash. Tokens are issued only on a match.",
        who: "By <b>Entra</b>.",
        tokenName: "Token request",
        claims: [
          ["code", "from step 2"],
          ["code_verifier", "<em>raw secret</em>"],
          ["grant_type", "authorization_code"],
        ],
      },
      {
        from: "entra",
        to: "app",
        label: "id + access + refresh",
        kind: "token",
        text: "Three tokens come back and stay on the backend.",
        who: "The backend is the one named in <b>userAuth.client</b>.",
        tokenName: "Entra tokens",
        claims: [
          ["aud", "api://orders-api"],
          ["scp", "profile"],
          ["sub", "the signed-in person"],
          ["stored", "server side only"],
        ],
      },
      {
        from: "app",
        to: "browser",
        label: "httpOnly session cookie",
        kind: "built",
        text: "The browser gets an httpOnly cookie, so page scripts never see a token.",
        who: "Set by the <b>backend</b>.",
        tokenName: "What the browser holds",
        claims: [
          ["cookie", "httpOnly, Secure, SameSite"],
          ["access token", "<em>none</em>"],
          ["readable by JS", "no"],
        ],
      },
    ],
  },

  {
    key: "obo",
    name: "Calling as the user (OBO)",
    yaml: [
      ["orders-api", "c"],
      ["consumes:", "d"],
      ["  - app: reports-api", "d"],
      ["", "c"],
      ["reports-api", "c"],
      ["provides:", "d"],
      ["  - name: exports", "d"],
      ["    auth: user", "d"],
      ["    allowedCallers:", "d"],
      ["      - app: orders-api", "d"],
    ],
    steps: [
      {
        from: "browser",
        to: "app",
        label: "session cookie",
        kind: "declared",
        text: "A person clicks export, and the backend finds the token it kept at sign-in.",
        who: "The token is <b>for this backend only</b>.",
        tokenName: "User token, at rest",
        claims: [
          ["aud", "<em>api://orders-api</em>"],
          ["sub", "the signed-in person"],
          ["scp", "profile"],
        ],
      },
      {
        from: "spireS",
        to: "spireA",
        label: "signs the SVID",
        kind: "built",
        text: "To act for the person, the backend first proves who it is.",
        who: "Starting at <b>SPIRE</b>. The pod has no client secret.",
        tokenName: "Where identity starts",
        claims: [
          ["trust domain", "homelab.local"],
          ["signing key", "server only"],
          ["agent holds", "no key"],
        ],
      },
      {
        from: "spireA",
        to: "sidecar",
        label: "CSI socket",
        kind: "built",
        text: "The agent checks with kubelet, and a fresh SVID lands in a file the app reads.",
        who: "The same <b>delivery</b> as any workload.",
        tokenName: "JWT-SVID",
        claims: [
          ["over", "Workload API, CSI-mounted socket"],
          ["sub", SPIFFE],
          ["aud", "api://AzureADTokenExchange"],
          ["used as", "client_assertion"],
        ],
      },
      {
        from: "app",
        to: "entra",
        label: "OBO exchange",
        kind: "token",
        text: "The app sends its own identity, the person's token, and the API it wants.",
        who: "Entra refuses a user token <b>issued for another app</b>.",
        tokenName: "OBO request",
        claims: [
          ["grant_type", "jwt-bearer"],
          ["client_assertion", "the SVID file"],
          ["assertion", "the user token"],
          ["scope", "api://reports-api/.default"],
        ],
      },
      {
        from: "entra",
        to: "app",
        label: "delegated token",
        kind: "token",
        text: "The new token still names the person, because reports-api declared auth: user.",
        who: "Granted by <b>reports-api's allowedCallers</b>.",
        tokenName: "Delegated access token",
        claims: [
          ["aud", "api://reports-api"],
          ["sub", "<em>still the person</em>"],
          ["scp", "<em>exports</em>"],
          ["roles", "absent"],
        ],
      },
      {
        from: "envoyO",
        to: "envoyO",
        label: "gates 1-3",
        kind: "gate",
        text: "The mesh checks the calling workload and ignores whose token it carries.",
        who: "Enforced by <b>Istio</b>.",
        tokenName: "Mesh check",
        claims: [
          ["principal", "spiffe://.../sa/orders-api"],
          ["gate 3", "PeerAuthentication, mTLS"],
          ["reads the token", "<em>no</em>"],
        ],
      },
      {
        from: "envoyO",
        to: "podRep",
        label: "scp check",
        kind: "declared",
        text: "reports-api sees a scope, so it knows a person is behind the call.",
        who: "<b>scp</b> means acting for someone, <b>roles</b> means acting as itself.",
        tokenName: "What the app sees",
        claims: [
          ["scp", "<em>exports</em>  (a string)"],
          ["roles", "absent (an array)"],
          ["sub", "the person, for the audit log"],
        ],
      },
    ],
  },

  {
    key: "aws",
    name: "Reaching AWS",
    yaml: [
      ["orders-api", "c"],
      ["objectStorageRefs:", "d"],
      ["  - name: order-docs", "d"],
      ["nosqlRef:", "d"],
      ["  name: order-index", "d"],
    ],
    steps: [
      {
        from: "xp",
        to: "iam",
        label: "at commit time",
        kind: "built",
        text: "The commit already created a role that trusts this pod's SPIFFE ID and can use one bucket.",
        who: "Built by <b>Crossplane</b>. Everything after this is runtime.",
        tokenName: "The trust policy",
        claims: [
          ["Federated", "https://oidc.mattjarrett.dev"],
          ["sub", `<em>${SPIFFE}</em>`],
          ["aud", "sts.amazonaws.com"],
          ["policy", "this bucket only"],
        ],
      },
      {
        from: "spireS",
        to: "spireA",
        label: "signs the SVID",
        kind: "built",
        text: "At runtime, identity starts at the SPIRE server as usual.",
        who: "Nothing here is <b>specific to AWS</b>.",
        tokenName: "Where identity starts",
        claims: [
          ["trust domain", "homelab.local"],
          ["signing key", "server only"],
          ["agent holds", "no key"],
        ],
      },
      {
        from: "spireA",
        to: "sidecar",
        label: "CSI socket",
        kind: "built",
        text: "The agent checks with kubelet and hands the sidecar a JWT-SVID for AWS STS.",
        who: "The <b>app container</b> is not on this path.",
        tokenName: "JWT-SVID",
        claims: [
          ["over", "Workload API, CSI-mounted socket"],
          ["sub", SPIFFE],
          ["aud", "<em>sts.amazonaws.com</em>"],
          ["exp", "in 5 minutes"],
        ],
      },
      {
        from: "sidecar",
        to: "sts",
        label: "AssumeRoleWithWebIdentity",
        kind: "token",
        text: "The sidecar calls STS itself, once per binding, asking for a different role each time.",
        who: "So each resource the pod uses gets <b>its own role</b>.",
        tokenName: "Presented to STS",
        claims: [
          ["token", "the JWT-SVID"],
          ["RoleArn", "arn:aws:iam::…:role/crossplane/…"],
          ["calls", "one per declared ref"],
        ],
      },
      {
        from: "sts",
        to: "oidc",
        label: "fetch public keys",
        kind: "built",
        dashed: true,
        text: "STS checks the signature against the cluster's keys and matches sub and aud exactly.",
        who: "Renaming the <b>service account</b> breaks access.",
        tokenName: "Being verified",
        claims: [
          ["signature", "against published JWKS"],
          ["sub", "exact match"],
          ["aud", "exact match"],
        ],
      },
      {
        from: "sts",
        to: "sidecar",
        label: "1h credentials",
        kind: "token",
        text: "Credentials come back and the sidecar refreshes them every 50 minutes.",
        who: "A <b>failed refresh</b> keeps the old file.",
        tokenName: "Short-lived credentials",
        claims: [
          ["access key", "expires in 1 hour"],
          ["refreshed at", "50 minutes"],
          ["on failure", "keep the old file, retry in 30s"],
        ],
      },
      {
        from: "sidecar",
        to: "sidecar",
        label: "writes profiles",
        kind: "built",
        text: "The sidecar writes one profile per binding to a shared file.",
        who: "Credentials stay on the <b>sidecar's</b> side.",
        tokenName: "At rest",
        claims: [
          ["file", "/aws-credentials/credentials"],
          ["profiles", "one per declared ref"],
          ["written by", "the sidecar"],
        ],
      },
      {
        from: "app",
        to: "s3",
        label: "signed request",
        kind: "declared",
        text: "The app calls S3 with a stock SDK using its profile. Its DynamoDB role cannot touch this bucket.",
        who: "One role per binding, so a compromised pod reaches <b>one resource</b>.",
        tokenName: "App code",
        claims: [
          ["env", "AWS_PROFILE_OBJECT_STORAGE_ORDER_DOCS"],
          ["reach", "this bucket"],
          ["cannot reach", "<em>the table, the database</em>"],
        ],
      },
    ],
  },
]
